[package]
name = "create2crunch"
version = "0.3.0"
authors = ["0age <0age@protonmail.com"]
edition = "2021"
rust-version = "1.85"
default-run = "create2crunch"

[dependencies]
alloy-primitives = { version = "0.5", features = ["rand"] }
byteorder = "1.5"
console = "0.15"
fs4 = "0.7"
ocl = { version = "0.19", optional = true }
metal = { version = "0.31", optional = true }
rand = "0.8"
rayon = "1.0"
rustc-hash = "1.1"
separator = "0.4.1"
terminal_size = "0.3.0"
tiny-keccak = "2.0"
clap = { version = "4.3.24", features = ["derive"] }

[[bin]]
name = "list_metal_devices"
path = "src/list_metal_devices.rs"

[profile.release]
opt-level = 3
lto = "fat"
strip = true
panic = "abort"
codegen-units = 1

[features]
default = ["opencl", "metal"]
opencl = ["dep:ocl"]
metal = ["dep:metal"]
asm = ["alloy-primitives/asm-keccak"]
